@base_address = http://localhost:5221/api/todos

GET {{base_address}}
Accept: application/json

###
POST {{base_address}}
Content-Type: application/json

{
   "title": "Task 2"
}

###
GET {{base_address}}/019942c1-de91-7c5e-b8b5-a12e88ba2cc2

### 
PUT {{base_address}}
Content-Type: application/json

{
  "id": "019942c1-de91-7c5e-b8b5-a12e88ba2cc2",
  "title": "Azure static web apps 2",
  "completed": false
}

###
DELETE {{base_address}}/019942c1-de91-7c5e-b8b5-a12e88ba2cc2
