// <auto-generated />
using CartesianExplosionExample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartesianExplosionExample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CartesianExplosionExample.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonAddress = "somewhere in Mumbai",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            PersonAddress = "some place in Mumbai",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            PersonAddress = "somewhere in Hyderabad",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            PersonAddress = "somewhere in Delhi",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            PersonAddress = "somewhere in Haryana",
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("CartesianExplosionExample.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonEmail")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonEmail = "ramesh.singh@example.com",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            PersonEmail = "singh.ramesh12@example.com",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            PersonEmail = "singh.ramesh13@work.com",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            PersonEmail = "mahesh.kumar@example.com",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            PersonEmail = "mahesh.kumar12@work.com",
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("CartesianExplosionExample.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ramesh",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Mahesh",
                            LastName = "Kumar"
                        });
                });

            modelBuilder.Entity("CartesianExplosionExample.Models.Address", b =>
                {
                    b.HasOne("CartesianExplosionExample.Models.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CartesianExplosionExample.Models.Email", b =>
                {
                    b.HasOne("CartesianExplosionExample.Models.Person", "Person")
                        .WithMany("Email")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CartesianExplosionExample.Models.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Email");
                });
#pragma warning restore 612, 618
        }
    }
}
