@base_address = http://localhost:5121

### Get employees
GET {{base_address}}/api/employees
Accept: application/json

### Get department's employees

GET {{base_address}}/api/departments/1/employees
Accept: application/json

### Get employees's skills
GET {{base_address}}/api/employees/1/skills
Accept: application/json
